### ISSUE TITLE
Uncaught TypeError: Unable to watch path

### ISSUE THREAD

**Issue by EdZava** [atom/atom-dark-syntax#12] opened 2015-03-19 09:50 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Unknown Windows Version
**Thrown From**: [atom-dark-syntax](https://github.com/atom/atom-dark-syntax) package, v0.26.0

### Stack Trace

Uncaught TypeError: Unable to watch path

```
At C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\src\workspace.js:520

TypeError: Unable to watch path
  at TypeError (native)
  at HandleWatcher.start (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\node_modules\pathwatcher\lib\main.js:66:29)
  at new HandleWatcher (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\node_modules\pathwatcher\lib\main.js:30:12)
  at new PathWatcher (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\node_modules\pathwatcher\lib\main.js:120:30)
  at Object.exports.watch (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\node_modules\pathwatcher\lib\main.js:179:12)
  at File.module.exports.File.subscribeToNativeChangeEvents (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\node_modules\pathwatcher\lib\file.js:410:109)
  at File.module.exports.File.willAddSubscription (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\node_modules\pathwatcher\lib\file.js:114:14)
  at File.willAddSubscription (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\node_modules\pathwatcher\lib\file.js:3:61)
  at File.module.exports.File.onDidChange (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\node_modules\pathwatcher\lib\file.js:94:12)
  at TextBuffer.module.exports.TextBuffer.subscribeToFile (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:1089:44)
  at TextBuffer.module.exports.TextBuffer.setPath (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:281:14)
  at new TextBuffer (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:100:14)
  at Project.module.exports.Project.buildBuffer (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\src\project.js:502:16)
  at Project.module.exports.Project.bufferForPath (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\src\project.js:476:63)
  at Project.module.exports.Project.open (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\src\project.js:430:19)
  at Workspace.module.exports.Workspace.openURIInPane (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\src\workspace.js:502:31)
  at Workspace.module.exports.Workspace.open (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\src\workspace.js:428:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\node_modules\tree-view\lib\tree-view.js:710:31)
  at TreeView.module.exports.TreeView.entryClicked (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\node_modules\tree-view\lib\tree-view.js:427:18)
  at tree-view-file.<anonymous> (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\node_modules\tree-view\lib\tree-view.js:178:26)
  at space-pen-div.jQuery.event.dispatch (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\node_modules\jquery\dist\jquery.js:4430:9)
  at space-pen-div.elemData.handle (C:\Users\Administrador\AppData\Local\atom\app-0.187.0\resources\app\node_modules\jquery\dist\jquery.js:4116:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-06-09 16:51
I think this is a duplicate of https://github.com/atom/atom/issues/6106, but the exception was incorrectly reported here.

**Closed by izuzak** 2015-06-09 16:51 UTC
