### ISSUE TITLE
Uncaught TypeError: Cannot read property  item  of undefined

### ISSUE THREAD

**Issue by firefoxForUser** [atom/atom-dark-syntax#23] opened 2015-11-08 10:13 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: [atom-dark-syntax](https://github.com/atom/atom-dark-syntax) package, v0.27.0

### Stack Trace

Uncaught TypeError: Cannot read property 'item' of undefined

```
At /C:/Users/user/.atom/packages/scroll-sync/lib/scroll-sync.coffee:62

TypeError: Cannot read property 'item' of undefined
  at ScrlSync.startTracking (C:\Users\user\.atom\packages\scroll-sync\lib\scroll-sync.coffee:34:19)
  at atom-workspace.subToggle.add.atom.commands.add.scroll-sync:toggle (C:\Users\user\.atom\packages\scroll-sync\lib\scroll-sync.coffee:19:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\user\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:243:29)
  at C:\Users\user\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\user\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\user\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-li.<anonymous> (C:\Users\user\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (C:\Users\user\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLOListElement.elemData.handle (C:\Users\user\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -3:46.3.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
  2x -3:08.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:23.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:16.4.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
     -0:08.4.0 scroll-sync:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
scroll-sync, v0.1.4

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-08 15:49
No idea how these issues get reported atom-dark-syntax even though the stacktrace clearly indicates scroll-sync...
@firefoxForUser this is a duplicate of mark-hahn/scroll-sync#12, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-08 15:49 UTC
