### ISSUE TITLE
Failed to load the remote-edit package

### ISSUE THREAD

**Issue by sunn7y** [atom/atom-dark-syntax#22] opened 2015-11-01 16:19 UTC
[Enter steps to reproduce below:]

1. Searched for Remote Edit plugin (https://atom.io/packages/remote-edit)
2. Tried to install it and received the error.

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: [atom-dark-syntax](https://github.com/atom/atom-dark-syntax) package, v0.27.0

### Stack Trace

Failed to load the remote-edit package

```
At TextEditor.registerDeserializer is not a function

TypeError: TextEditor.registerDeserializer is not a function
  at C:\Users\DimaS\.atom\packages\remote-edit\lib\model\remote-edit-editor.coffee:26:16
  at Object.<anonymous> (C:\Users\DimaS\.atom\packages\remote-edit\lib\model\remote-edit-editor.coffee:253:5)
  at Object.<anonymous> (C:\Users\DimaS\.atom\packages\remote-edit\lib\model\remote-edit-editor.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (D:\Dropbox\Atom\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\DimaS\.atom\packages\remote-edit\lib\main.coffee:2:20)
  at Object.<anonymous> (C:\Users\DimaS\.atom\packages\remote-edit\lib\main.coffee:2:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (D:\Dropbox\Atom\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (D:\Dropbox\Atom\resources\app.asar\src\package.js:725:34)
  at D:\Dropbox\Atom\resources\app.asar\src\package.js:176:28
  at Package.module.exports.Package.measure (D:\Dropbox\Atom\resources\app.asar\src\package.js:153:15)
  at Package.module.exports.Package.load (D:\Dropbox\Atom\resources\app.asar\src\package.js:167:12)
  at PackageManager.module.exports.PackageManager.loadPackage (D:\Dropbox\Atom\resources\app.asar\src\package-manager.js:396:14)
  at PackageManager.module.exports.PackageManager.activatePackage (D:\Dropbox\Atom\resources\app.asar\src\package-manager.js:473:30)
  at D:\Dropbox\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:444:29
  at exit (D:\Dropbox\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
  at triggerExitCallback (D:\Dropbox\Atom\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (D:\Dropbox\Atom\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
     -8:45.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -6:36.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:30.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:06.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:59.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -4:44.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:40 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:03.2.0 editor:select-line (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:58.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:55.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:54.2.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -2:52.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -2:45.8.0 core:move-left (atom-text-editor.editor.mini.is-focused)
  3x -2:44.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:45.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:43.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
color-picker, v2.0.13
editor-stats, v0.17.0
editorconfig, v1.2.1
emmet, v2.3.13
file-icons, v1.6.11
highlight-line, v0.11.0
javascript-snippets, v1.0.0
jshint, v1.8.3
minimap, v4.15.2
pretty-json, v0.4.1
remote-edit, v1.8.21

# Dev
No dev packages
```

**Comment by thomasjo** [comment] 2015-11-04 05:27
Looks like a duplicate of https://github.com/sveale/remote-edit/issues/138.

---
@atom/feedback Another incorrectly attributed exception.

**Closed by thomasjo** 2015-11-04 05:27 UTC
